### ISSUE TITLE
README file refactoring

### ISSUE THREAD

**Issue by Pavel-Durov** [hrik2001/macuninstaller#5]
I think that there are slight improvements need to be made in README file:

1. Running `python ./cli.py -p /Applications/QuickTime\ Player.app/`
Lists application paths, but there's no removal option, therefore 

> macuninstaller is a python script that was written to uninstall mac apps. This script finds all the related files and folders and deletes them for you

Should be changed to something more appropriate - identifying that you can uninstall only through the GUI version (aka macuninstaller.py)

2. Supported Python version Identification should be added to README.
You get Python version prompt when running with an unsupported version - but it's only after you've downloaded and run the script.

**Comment by hrik2001** [comment]
Added uninstallation support from CLI so no worries ^^
